apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: permissions
spec:
  version: {{ .TagName }}
  homepage: https://github.com/garethjevans/kubectl-permissions
  shortDescription: Display service account permissions
  description: |
    This plugin shows all permissions from Roles/ClusterRoles for the referenced service account.
  caveats: |
    * For resources that are not in default namespace, currently you must
      specify -n/--namespace explicitly (the current namespace setting is not
      yet used).
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/garethjevans/kubectl-permissions/releases/download/{{ .TagName }}/kubectl-permissions_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-permissions
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/garethjevans/kubectl-permissions/releases/download/{{ .TagName }}/kubectl-permissions_{{ .TagName }}_darwin_arm64.tar.gz" .TagName }}
    bin: kubectl-permissions
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/garethjevans/kubectl-permissions/releases/download/{{ .TagName }}/kubectl-permissions_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-permissions
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/garethjevans/kubectl-permissions/releases/download/{{ .TagName }}/kubectl-permissions_{{ .TagName }}_windows_amd64.tar.gz" .TagName }}
    bin: kubectl-permissions.exe
