apiVersion: v1
kind: Namespace
metadata:
  name: test-namespace
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: test-namespace
  name: sa-under-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: test-namespace
  name: invalid-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-roles
subjects:
- kind: ServiceAccount
  namespace: test-namespace
  name: sa-under-test
roleRef:
  kind: ClusterRole
  name: cluster-level-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-level-role
rules:
- apiGroups: ['']
  resources: ['pods', 'pods/log', 'services', 'configmaps']
  verbs: ['get', 'watch', 'list']
- apiGroups: ['apps']
  resources: ['deployments', 'replicasets']
  verbs: ['get', 'watch', 'list']
- apiGroups: ['networking.k8s.io']
  resources: ['ingresses']
  verbs: ['get']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespaced-role
  namespace: test-namespace
rules:  
- apiGroups: ['source.toolkit.fluxcd.io']
  resources:
  - gitrepositories
  verbs: ['get', 'watch', 'list']
- apiGroups: ['kpack.io']
  resources:
  - images
  - builds
  verbs: ['get', 'watch', 'list']
- apiGroups: ['tekton.dev']
  resources:
  - taskruns
  - pipelineruns
  verbs: ['get', 'watch', 'list']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: invalid-role
  namespace: test-namespace
rules:
- apiGroups: ['bingbong.io']
  resources:
  - something
  verbs: ['get', 'watch', 'list']
- apiGroups: ['tekton.dev']
  resources:
  - invalid
  verbs: ['get']
- apiGroups: ['source.toolkit.fluxcd.io']
  resources:
  - gitrepositories
  verbs: ['laugh']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespaced-roles
  namespace: test-namespace
subjects:
- kind: ServiceAccount
  namespace: test-namespace
  name: sa-under-test
roleRef:
  kind: Role
  name: namespaced-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: missing-role-binding
  namespace: test-namespace
subjects:
- kind: ServiceAccount
  namespace: test-namespace
  name: invalid-sa
roleRef:
  kind: Role
  name: missing-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: missing-role-binding2
  namespace: test-namespace
subjects:
  - kind: ServiceAccount
    namespace: test-namespace
    name: invalid-sa
roleRef:
  kind: Role
  name: invalid-role
  apiGroup: rbac.authorization.k8s.io
