---
name: Testing
on:
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        kubernetes_version:
          - "kindest/node:v1.25.2"
          - "kindest/node:v1.24.6"
          - "kindest/node:v1.23.13"
          - "kindest/node:v1.22.15"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: |
          make build
          mv kubectl-permissions /usr/local/bin   

      - name: Install Kubectl
        uses: azure/setup-kubectl@v1

      - name: Create Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          node_image: ${{ matrix.kubernetes_version }}
          wait: 120s

      - name: Deploy RBAC
        run: |
          kubectl apply -f example-rbac.yaml
          kubectl permissions sa-under-test -n test-namespace
